CATKW101	Float	${FS1_inc}	Incidence angle of beam surface FS1 [deg]
CATKW102	Float	${FS1_pos_x}	Camera Coordinate System x coordinate of beam at surface FS1 [mm]
CATKW103	Float	${FS1_pos_y}	Camera Coordinate System y coordinate of beam at surface FS1 [mm]
CATKW104	Float	${FS2_inc}	Incidence angle of beam surface FS2 [deg]
CATKW105	Float	${FS2_pos_x}	Camera Coordinate System x coordinate of beam at surface FS2 [mm]
CATKW106	Float	${FS2_pos_y}	Camera Coordinate System y coordinate of beam at surface FS2 [mm]
