CATKW101	Float	${CCOBBCAM}	Camera coordinate value for carriage axis B of CCOB-Narrow projector [deg]
CATKW102	Float	${CCOBBPOS}	Motor (hardware) coordinate value for carriage axis B of CCOB-Narrow projector [deg]
CATKW103	Float	${CCOBUCAM}	Camera coordinate value for carriage axis U of CCOB-Narrow projector [deg]
CATKW104	Float	${CCOBUPOS}	Motor (hardware) coordinate value for carriage axis U of CCOB-Narrow projector [deg]
CATKW105	Float	${CCOBXCAM}	Camera coordinate value for carriage axis X of CCOB-Narrow projector [mm]
CATKW106	Float	${CCOBXPOS}	Motor (hardware) coordinate value for carriage axis X of CCOB-Narrow projector [mm]
CATKW107	Float	${CCOBYCAM}	Camera coordinate value for carriage axis Y of CCOB-Narrow projector [mm]
CATKW108	Float	${CCOBYPOS}	Motor (hardware) coordinate value for carriage axis Y of CCOB-Narrow projector [mm]
CATKW109	Float	${CCOB_L1S1_separation}	Local separation between CCOB Carriage plane and Camera L1S1 plane
CATKW10A	Float	${CCOB_inc}	Incidence angle of beam surface CCOB [deg]
CATKW10B	Float	${CCOB_pos_x}	Camera Coordinate System x coordinate of beam at surface CCOB [mm]
CATKW10C	Float	${CCOB_pos_y}	Camera Coordinate System y coordinate of beam at surface CCOB [mm]
CATKW10D	Float	${FP_inc}	Incidence angle of beam surface FP [deg]
CATKW10E	Float	${FP_pos_x}	Camera Coordinate System x coordinate of beam at surface FP [mm]
CATKW10F	Float	${FP_pos_y}	Camera Coordinate System y coordinate of beam at surface FP [mm]
CATKW110	Float	${FS1_inc}	Incidence angle of beam surface FS1 [deg]
CATKW111	Float	${FS1_pos_x}	Camera Coordinate System x coordinate of beam at surface FS1 [mm]
CATKW112	Float	${FS1_pos_y}	Camera Coordinate System y coordinate of beam at surface FS1 [mm]
CATKW113	Float	${FS2_inc}	Incidence angle of beam surface FS2 [deg]
CATKW114	Float	${FS2_pos_x}	Camera Coordinate System x coordinate of beam at surface FS2 [mm]
CATKW115	Float	${FS2_pos_y}	Camera Coordinate System y coordinate of beam at surface FS2 [mm]
CATKW116	Float	${L1S1_inc}	Incidence angle of beam surface L1S1 [deg]
CATKW117	Float	${L1S1_pos_x}	Camera Coordinate System x coordinate of beam at surface L1S1 [mm]
CATKW118	Float	${L1S1_pos_y}	Camera Coordinate System y coordinate of beam at surface L1S1 [mm]
CATKW119	Float	${L1S2_inc}	Incidence angle of beam surface L1S2 [deg]
CATKW11A	Float	${L1S2_pos_x}	Camera Coordinate System x coordinate of beam at surface L1S2 [mm]
CATKW11B	Float	${L1S2_pos_y}	Camera Coordinate System y coordinate of beam at surface L1S2 [mm]
CATKW11C	Float	${L2S1_inc}	Incidence angle of beam surface L2S1 [deg]
CATKW11D	Float	${L2S1_pos_x}	Camera Coordinate System x coordinate of beam at surface L2S1 [mm]
CATKW11E	Float	${L2S1_pos_y}	Camera Coordinate System y coordinate of beam at surface L2S1 [mm]
CATKW11F	Float	${L2S2_inc}	Incidence angle of beam surface L2S2 [deg]
CATKW120	Float	${L2S2_pos_x}	Camera Coordinate System x coordinate of beam at surface L2S2 [mm]
CATKW121	Float	${L2S2_pos_y}	Camera Coordinate System y coordinate of beam at surface L2S2 [mm]
CATKW122	Float	${L3S1_inc}	Incidence angle of beam surface L3S1 [deg]
CATKW123	Float	${L3S1_pos_x}	Camera Coordinate System x coordinate of beam at surface L3S1 [mm]
CATKW124	Float	${L3S1_pos_y}	Camera Coordinate System y coordinate of beam at surface L3S1 [mm]
CATKW125	Float	${L3S2_inc}	Incidence angle of beam surface L3S2 [deg]
CATKW126	Float	${L3S2_pos_x}	Camera Coordinate System x coordinate of beam at surface L3S2 [mm]
CATKW127	Float	${L3S2_pos_y}	Camera Coordinate System y coordinate of beam at surface L3S2 [mm]
CATKW128	Float	${best}	Convergence test between target and raytraced position at focal plane for plan [mm]
CATKW129	Float	${expose}	High speed shutter requested open time [sec]
CATKW12A	Float	${exptime}	Requested focal plane exposure time [sec]
CATKW12B	String	${filter}	Filter optic model used for computing this CCOB beam pointing [ugrizy,none]
CATKW12C	String	${id}	Unique CCOB-narrow exposure catalog entry ID number for registration [hex]
CATKW12D	Float	${lambda}	Hyperchromator setting for wavelength output [nm]
CATKW12E	Float	${plan_pd_current}	Photodiode current used in estimating shutter time (may be different from actual due to aperture adjustment or lamp condition [nA]
CATKW12F	String	${rebs}	REB combination list requested for readout and image handling []
CATKW130	String	${sens}	Sensor address used in computing target for this CCOB beam pointing, [Rij_Skl[_Cmn]]
CATKW131	Float	${target_phot_per_pix}	Target photon level target for this exposure's flat top section of CCOB-narrow beam - cf. local calibration file vs. plan file [inc.phot/pixel]
CATKW132	Float	${total_phots}	Target total photons approaching focal plane for this exposure - cf. local calibration file vs. plan file [photons]
